export const specificnovelSearch = [
  {
    noverId: 1,
    title: "신과 함께 레벨업",
    description: "흑아인",
    author: "완결",
    genre: "판타지",
    grade: false,
    thumbnail: "/assets/images/dummy/bestItem01.png",
    startDate: "1972-12-10",
    serializationDays: 1,
    views: 1632178341,
    serializationStatus: "연재중",
    tag: [
      { id: 1, name: "로맨스" },
      { id: 2, name: "짝사랑" },
      { id: 3, name: "사랑" },
    ],
    scheduleld: 1,
    starRating: 9.8,
  },
  {
    noverId: 2,
    title: "111111신과 함께 레벨업",
    description: "11흑아인",
    author: "11완결",
    genre: "11판타지",
    grade: false,
    thumbnail: "/assets/images/dummy/bestItem01.png",
    startDate: "1972-12-10",
    serializationDays: 1,
    views: 1632178341,
    serializationStatus: "연재중",
    tag: [
      { id: 1, name: "로맨스" },
      { id: 2, name: "짝사랑" },
      { id: 3, name: "사랑" },
    ],
    scheduleld: 1,
    starRating: 9.8,
  },
  {
    noverId: 3,
    title: "111111신과 함께 레벨업",
    description: "11흑아인",
    author: "11완결",
    genre: "11판타지",
    grade: false,
    thumbnail: "/assets/images/dummy/bestItem01.png",
    startDate: "1972-12-10",
    serializationDays: 1,
    views: 1632178341,
    serializationStatus: "연재중",
    tag: [
      { id: 1, name: "로맨스" },
      { id: 2, name: "짝사랑" },
      { id: 3, name: "사랑" },
    ],
    scheduleld: 1,
    starRating: 9.8,
  },
];

export const episodeCardData = [
  {
    noverId: 1,
    episode: [
      {
        id: 1,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 2,
        name: "흑아인1111111",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 3,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 4,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
      },
      {
        id: 5,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 6,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 7,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
    ],
  },
  {
    noverId: 2,
    episode: [
      {
        id: 1,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 2,
        name: "흑아인1111111",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 3,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 4,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 5,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 6,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 7,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
    ],
  },
  {
    noverId: 3,
    episode: [
      {
        id: 1,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 2,
        name: "흑아인1111111",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 3,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 4,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 5,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 6,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
      {
        id: 7,
        name: "흑아인",
        free: "무료",
        registrationData: "2020-03-21",
        starRating: 9.5,
        thumbnailUrl: "/assets/images/dummy/bestItem01.png",
      },
    ],
  },
];
